Sc 720 expand unit tests for topos related modules
InverterNetwork/inverter-contracts pull request #676
Opened 2024-10-16 13:40 UTC by FHieser

@Zitzak there is still a todo in there. Can you take a look, because I didnt quite understand why I couldnt increase the testvalue here.
Otherwise the Buy, buyFor, Sell and SellFor of the Restricted_Repayer_seizable are not tested, didnt know if we wanted to do that still or not
The coverage is still over 96% fyi

2024-10-21 12:51 UTC, Zitzak requested changes

2024-10-21 12:51 UTC, Zitzak commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo this does not work, as the address of the simultaneously deployed tokenVault is not known at the point of deployment
I see your point. Why not just remove the section :)

2024-10-21 12:51 UTC, Zitzak commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo Marvin G couldnt find a test for this
Unclear why this comment found its way back into the file. Also wasn't the idea of the PR to add testing?

2024-10-21 12:51 UTC, Zitzak commented on test/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.t.sol
> +    function testWithdrawProjectCollateralFee_revertsGivenCallerIsOrchestratorAdmin(
Also modifier in place test right? Function name is not reflecting this

2024-10-21 12:51 UTC, Zitzak commented on test/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_v1.t.sol
> +    function testTransferOrchestratorToken_OnlyPaymentClientModifierSet(
Function name different than the other tests

2024-10-22 07:13 UTC, FHieser commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo this does not work, as the address of the simultaneously deployed tokenVault is not known at the point of deployment
Because I commented this in the initial PR and you removed it again :see_no_evil:

2024-10-22 07:14 UTC, FHieser commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo Marvin G couldnt find a test for this
Yeah dont know why this was back here again :man_shrugging:

2024-10-22 07:29 UTC, FHieser commented on test/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.t.sol
> +    function testWithdrawProjectCollateralFee_revertsGivenCallerIsOrchestratorAdmin(
Nope
This revert is not bound to a modifier, but the function in general should revert if called
technically we could remove the modifier that restricts calling the function in general.

2024-10-22 07:37 UTC, FHieser commented on test/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_v1.t.sol
> +    function testTransferOrchestratorToken_OnlyPaymentClientModifierSet(
Renamed to Modifier in Position test
Thats what you had in mind here right?

2024-10-22 07:38 UTC, FHieser commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo this does not work, as the address of the simultaneously deployed tokenVault is not known at the point of deployment
Removed it

2024-10-22 07:38 UTC, FHieser commented on src/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_Restricted_Repayer_Seizable_v1.sol
> +        //@todo Marvin G couldnt find a test for this
Added the tests

2024-10-22 11:30 UTC, Zitzak commented on test/modules/fundingManager/bondingCurve/FM_BC_BondingSurface_Redeeming_v1.t.sol
> +    function testTransferOrchestratorToken_OnlyPaymentClientModifierSet(
Yes ser

2024-10-22 11:30 UTC, Zitzak approved these changes
LGTM

2024-10-22 12:49 UTC, merged