Fix: Resolve Module Address Collisions
InverterNetwork/inverter-contracts pull request #690
Opened 2024-11-15 11:42 UTC by marvinkruse

**Why does this PR exist?**

2024-11-26 12:53 UTC, FHieser approved these changes

2024-11-26 12:54 UTC, FHieser commented
![9boukq](https://github.com/user-attachments/assets/dd0ed63f-8365-4e2e-9ab0-ceaf500bee61)

2024-11-26 12:54 UTC, FHieser requested changes
Need tests

2025-01-16 09:43 UTC, Zitzak commented
How to move forward with this PR? How does having these changes un-merged effect our deployments? @marvinkruse @FHieser @0xNuggan

2025-04-25 14:08 UTC, FHieser commented
@marvinkruse what is the state of this PR?

2025-04-29 13:41 UTC, marvinkruse commented
Closing for now, will reopen if we decide to use this so that we can have a cleaner stack of PRs for now.

2025-04-29 13:41 UTC, closed without merging