Oracle Based Funding Manager contract structure defined
InverterNetwork/inverter-contracts pull request #691
Opened 2024-11-15 15:56 UTC by vendrell46

This is a WIP, so I've created this PR so that we can review:
- Folder structure
- Contract Inheritance
- Imports
- Naming convention
- Functions proposed for `IOraclePrice_v1` interface (there might be more, but for now it'd be good to know if those added currently are valid)
- Functions proposed for `IERC20Issuance_blacklist_v1` interface

There hasn't been any actual contract implementation done yet, so please ignore function/constructor's implementation.

2024-11-21 15:18 UTC, FHieser requested changes
The only thing is the Interface adaption that is still needed. 
Apart from that looks good to me :+1:

2024-11-21 15:18 UTC, FHieser commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IERC20PaymentClientBase_v1
As discussed on slack IFM_PC_Oracle_Redeeming_v1 needs to inherit the IFundingmanager interface, the IERC20PaymentClientBase_v1 and the RedeemingInterface. 
So the only "original" part of the Interface would be the Oracle functionality that should be added here I think, as that is the only new stuff that the other interfaces dont provide

2024-11-21 15:18 UTC, FHieser commented on src/modules/fundingManager/oracle/OraclePrice_v1.sol
> +contract OraclePrice_v1 is IOraclePrice_v1 {
Interested for your opinion:
With the explanation I gave in regards of the functionality of this contract would you say that the name fits? If you could rename it what would you choose here?

2024-11-21 15:52 UTC, vendrell46 commented on src/modules/fundingManager/oracle/OraclePrice_v1.sol
> +contract OraclePrice_v1 is IOraclePrice_v1 {
I'm still not 100% what exactly will this contract end up doing, so hard to guess now. Probably we can leave it as it is and see if we stick to it once we have the Oracle thing clear.

2024-11-21 15:54 UTC, vendrell46 commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IERC20PaymentClientBase_v1
done

2024-11-22 08:36 UTC, FHieser requested changes

2024-11-22 08:36 UTC, FHieser commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IERC20PaymentClientBase_v1
You are still missing the IRedeemingBondingCurveBase_v1 as inheritance here

2024-11-22 19:47 UTC, vendrell46 commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IERC20PaymentClientBase_v1
done, thanks

2024-11-25 15:14 UTC, Zitzak commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IRedeemingBondingCurveBase_v1
Why are we inheriting also the redeeming base interface here? Just curious as I wasn't expecting it

2024-11-25 15:23 UTC, Zitzak approved these changes
LGTM, great work!

2024-11-25 15:23 UTC, Zitzak commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_Oracle_Redeeming_v1.sol
> +    IRedeemingBondingCurveBase_v1
Ahh just got my question answered by seeing the new update in the code of conduct. Consider this comment resolved

2024-11-25 15:32 UTC, Zitzak commented
The purpose of this PR has been to align on the inheritance setup. @FHieser and I approved the setup (marked by my approval)

However the PR will be closed to comply with the agreement that only PR that pass the CI will be merged into the feature branch. A new PR will be opened soon

2024-11-25 15:32 UTC, closed without merging