Sc 848 task copy fee adaption from topos to dev
InverterNetwork/inverter-contracts pull request #700
Opened 2024-12-05 09:51 UTC by FHieser

Abstracts the collection of the projectfee into its own function
Directly copied from the topos branch #667

2024-12-05 10:08 UTC, Zitzak requested changes

2024-12-05 10:08 UTC, Zitzak commented on test/modules/fundingManager/bondingCurve/abstracts/BondingCurveBase_v1.t.sol
> +        bondingCurveFundingManager.exposed_projectFeeCollected(
Could you please add the emit tests, as well as add it to the gherkin

2024-12-05 16:58 UTC, FHieser commented
@Zitzak could you pls rereview

2024-12-05 17:26 UTC, Zitzak approved these changes

2024-12-05 17:27 UTC, merged

2024-12-06 01:04 UTC, marvinkruse commented
Just saw this was merged without me being a reviewer, three things:

(1) Why is the downstream contract not version upgraded?
If `BondingCurveBase_v1` changes, the version of all contracts inheriting it also needs to change, i.e. `FM_BC_Bancor_Redeeming_VirtualSupply_v1` and `FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1`, as the code of these also changed subsequently, speaking from a contract standpoint and it not the same anymore, so it needs changing.

(2) The `_projectFeeCollected` function Natspec should have `@notice`, not just `@dev`

(3) The name of the merged commit is not as we agreed.

Please mark me as a reviewer for **any** PRs that go into **dev** until we are all up to speed on using the Inverter Standard, otherwise it's just double work. (@FHieser @Zitzak)

2024-12-06 01:07 UTC, marvinkruse commented
This merge-to-dev-commit should be reverted, or did you guys already rebase too many other PRs?

2024-12-06 11:52 UTC, Zitzak commented
I did merge it into the feature branch for the External price funding manager. However if you would like to change it than please go ahead and I force push it to the feature branch @marvinkruse