[Audit] FM_PC_ExternalPrice_Redeeming, LM_ManualExternalPriceSetter_v1,
InverterNetwork/inverter-contracts pull request #704
Opened 2024-12-20 15:39 UTC by Zitzak

## What needs to be audit.
The contracts that need to be audited are
**Funding Manager**

- src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol

**Logic Module**

- src/modules/logicModule/LM_Oracle_Permissioned_v1.sol

**Payment Processor**

- src/modules/paymentProcessor/PP_Queue_v1.sol
- src/modules/paymentProcessor/interfaces/IPP_Queue_ManualExecution_v1.sol

**Blacklist Token**

- src/external/token/ERC20Issuance_Blacklist_v1.sol

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    uint[50] private __gap;
The convention is to put the gap at the end of the file, so you never accidentally put anything after it. However that is just the convetion and though I'd reccomend to follow it, it's not a necessity.

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    function setIssuancePrice(uint price_)
Since issuance and redemption price are likely to move together, you could consider either uniting the setters from them, or adding a setter which atomically updates both, as in some cases you may need the updates to happen atomically.

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    function setIssuancePrice(uint price_)
For example if buy price was 2, and sell price was 1, but now they're adjusted to 4 buy and 3 sell, you don't want the sell price updated before the buy price, so you either have to wait until new buy price is confirmed, or do the change atomically.

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        _redemptionPrice = _normalizePrice(price_, _issuanceTokenDecimals);
According to the docs above, this should be the _collateralTokenDecimals, not _issuanceTokenDecimals.

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        emit RedemptionPriceSet(price_, block.timestamp);
You could usually get the block time of the event when reading it, which makes it a waste of gas to also emit it here (and in the other events as well)

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        }
This can never happen since the setter disallows it

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        }
This can never happen since the setter disallows it

2024-12-27 14:57 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    function _normalizePrice(uint price_, uint8 tokenDecimals_)
Why do all this in the first place though? Price could just be defined in the collateral token, since this is what the price actually is (issuance and redemption are both denominated in the collateral token, ie. Buy 1 EUR for 1.1 USD, sell 1 EUR for 1.05 USD, both prices are denominated in USD, and it makes sense to just keep prices as USD all the way through).

2024-12-27 14:57 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +    function isBlacklistManager(address account_) public view returns (bool) {
Can be marked external. Or the mapping itself could just be public

2024-12-27 14:57 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        }
This will fail anyway in isBlacklisted since address 0 can't be blacklisted

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    function deductProcessedRedemptionAmount(uint processedRedemptionAmount_)
This does not seem to be implemented currently in any of the contracts

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    uint private _nextOrderId;
Why do you need both? It seems they serve the same purpose and one can be known from the other.

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            recipient: _msgSender(),
Recipient should be the receiver_ not msg.sender

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            RedemptionState.PROCESSING
The other states don't seem to really be used

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        _handleCollateralTokensAfterSell(_receiver, collateralRedeemAmount);
You could just remove this call here

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        uint redemptionAmount_ = collateralRedeemAmount_ - issuanceFeeAmount_;
The collateralRedeemAmount_ is already post fee, which means this essentially deducts the fee twice and is wrong

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        }
Could just remove this as it is unused in this implementation

2024-12-27 14:57 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
issuanceFeeAmount is just one of the fees charged, it's unclear why it does not pass all fees combined

2024-12-27 17:10 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        }
the whole zero address check here is a bit useless as it will not matter if the zero address is balcklisted or not

2024-12-27 17:11 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +            revert ERC20Issuance_Blacklist_BatchLimitExceeded(
what is the point of limiting the batch to this arbitrary number. If the manager wants to add 400 addresses, is that a problem?

2024-12-27 17:13 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
what is the purpose of this logic? Is there a problem i fthe blacklist manager adds move than BATCH_LIMIT addresses to the blacklist?

2024-12-27 17:13 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        onlyBlacklistManager
can be removed, as addToBlacklist already has this check

2024-12-27 17:14 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
see comment above - it is unclear what the point of this extra check is

2024-12-27 17:14 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        onlyBlacklistManager
can be removed as it is already checkd in removeFromBlacklist

2024-12-27 18:01 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        buyingIsEnabled
buyingisenabled is also checked in super.buyFor, so it could be removed here

2024-12-27 18:06 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    function deductProcessedRedemptionAmount(uint processedRedemptionAmount_)
This makes the _openRedemptionAmount variable basically useless, so it is probably a bug

2024-12-27 19:40 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
(jelle:) I thnk it is because the protocolFeeAmount, projectFeeAmount are taken from the collateral, and the issaunceFee from the issuance token.

2024-12-27 20:14 UTC, omega-audits commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +contract LM_ManualExternalPriceSetter_v1 is
there seems to be no test touching this contract

2024-12-27 20:18 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +// SPDX-License-Identifier: LGPL-3.0-only
There are no tests covering this contract, and we believe we have found some errors that would definitely have been caught with a test.

2025-01-03 14:01 UTC, vendrell46 commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        _redemptionPrice = _normalizePrice(price_, _issuanceTokenDecimals);
I'm confident the implementation is correct as is. 

For redemption, we're pricing 'how many collateral tokens you get for 1 issuance token', so the input price should be in issuance token decimals, as stated in the documentation. This maintains consistency with the pricing model where 1 unit is always denominated in the issuance token.

2025-01-03 14:38 UTC, vendrell46 commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
It's merely a DoS protection. While the chances are low, it is still worth having it. 

If a blacklist manager needs to add more than BATCH_LIMIT addresses, they can simply split it into multiple transactions.

2025-01-03 14:39 UTC, vendrell46 commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
same as above

2025-01-03 14:44 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    uint private _nextOrderId;
mainly we saw it as having two different purposes even though you are right that we could derive one from the other. But having them both we have that:

- `_orderId` represents the currently active/processing order.
- `_nextOrderId` is an incrementing counter that ensures each new order gets a unique ID.

2025-01-03 14:47 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        buyingIsEnabled
from my point of view, we need it because the function is public and could be called directly.

2025-01-03 14:53 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        uint redemptionAmount_ = collateralRedeemAmount_ - issuanceFeeAmount_;
good catch

2025-01-03 14:56 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            RedemptionState.PROCESSING
It will be used when integrated with a different module

2025-01-03 15:03 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        }
makes sense

2025-01-03 15:07 UTC, vendrell46 commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        _handleCollateralTokensAfterSell(_receiver, collateralRedeemAmount);
true

2025-01-08 14:35 UTC, Zitzak commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    function _normalizePrice(uint price_, uint8 tokenDecimals_)
Currently discussing internally. Will be following up on it

2025-01-08 14:42 UTC, Zitzak commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +    function isBlacklistManager(address account_) public view returns (bool) {
Small context @omega-audits, we make all state variable private by default and add explicit getters for it. Code has been changed as you suggested

2025-01-08 14:49 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    function deductProcessedRedemptionAmount(uint processedRedemptionAmount_)
The FM_PC contract will be coupled with a queue based Payment Processor, which is almost up for review. This contract will be calling the function mentioned above. However I do see an issue with it now if a different PP is paired with this FM. Will be addressed differently

2025-01-08 14:58 UTC, Zitzak commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        _redemptionPrice = _normalizePrice(price_, _issuanceTokenDecimals);
Feeds into the conversation about using the collateral price for all calculation [see comment](https://github.com/InverterNetwork/contracts/pull/704#discussion_r1897340470)

2025-01-08 14:59 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +    uint private _nextOrderId;
I see the point in regards to gas optimization. The `nextOrderId` will be removed

2025-01-08 15:03 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            RedemptionState.PROCESSING
An indexer will be used to track state changes and redemption orders which will be visualized within our admin panel.

However the `block.timestamp` can probably be removed as recommended elsewhere, as those can be retrieved from the event

2025-01-08 15:16 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
You are right (jelle), we charge different fees here. The project fee can only be charged from the collateral while the protocol fee can be charge from issuance and collateral.

The event emitting the fee amount in the `_createAndEmitOrder` function serves the purpose of giving the project information they need for their users, as well as their admin panel.

**However** this question did reveal to me that what we should have been passing into the function is not the `issuanceFeeAmount` (which is part of the protocol fee), but the `projectFeeAmount`. So turns out to still be a great catch @omega-audits

2025-01-08 15:20 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        buyingIsEnabled
I have to agree here with @omega-audits, as calling this function directly, as you're mentioning, will direct to the base `buyFor` where the modifier is located.

Could you please expand a bit on your point @vendrell46. Thank you

2025-01-08 15:22 UTC, Zitzak commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +contract LM_ManualExternalPriceSetter_v1 is
Tests have been written but were on a different branch. We decided to move forward with the audit (without the tests being on the feature branch) due to the time crunch. However the tests will be in the feature branch for the second audit

2025-01-08 15:22 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +// SPDX-License-Identifier: LGPL-3.0-only
See comments above. Nonetheless, some could have indeed be found in the testing that was done

2025-01-08 16:18 UTC, leeftk commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
I don't actually think this is necessary tbh, I believe this can be removed as the manager themselves can just submit  addresses in batches themselves if they end up hitting the gas limit with too many.

2025-01-14 05:02 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +        buyingIsEnabled
```
    function buyFor(address _receiver, uint _depositAmount, uint _minAmountOut)
        public
        virtual
        override(BondingCurveBase_v1)
        validReceiver(_receiver)
        buyingIsEnabled
    {
        (uint amountIssued, uint collateralFeeAmount) =
            _buyOrder(_receiver, _depositAmount, _minAmountOut);
        _addVirtualIssuanceAmount(amountIssued);
        _addVirtualCollateralAmount(_depositAmount - collateralFeeAmount);
    }
    ```
    
    This is correct this is redundant and should be removed.

2025-01-20 10:16 UTC, Zitzak commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +        }
Just finding out that this could be triggered in the situation where the contract has been initialized, but no price has been set yet. Then it would revert instead of returning 0. Is this something we should keep, or maybe enforce setting an initial price when initializing the module. Wdyt? @leeftk @vendrell46

2025-03-02 18:03 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        if (totalAccounts > BATCH_LIMIT) {
Yes that is what we'd recommend

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        }
If client has to be the _msgSender it will never be address(0) anyway (and if it is it'll revert)

2025-03-06 11:02 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        __Module_orchestrator.paymentProcessor().processPayments(
The benefit of a queue is to execute multiple orders at once, but this will just process each order when it's added, which makes the whole queue logic unused.

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        _executePaymentQueue(address(client_));
The benefit of a queue is to execute multiple orders at once, but this will execute the orders as soon as they are added to the queue. It would make more sense to separate the execution logic from adding to the queue

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
If firstId != LinkedIdList._SENTINEL then _processNextOrder will return false, so the entire tracking here of firstId is essentially unnecessary, the function could be written as:
```
        uint processedCount;
        while (_processNextOrder(client_))
        {
            ++processedCount;
        }

        emit PaymentQueueExecuted(_msgSender(), client_, processedCount);
```

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
Another point, _processNextOrder may return false in various cases, but not in all of them it's needed to stop the execution of the rest of the queue. For example, if the payment fails for a specific order, it doesn't mean you should stop here and not execute the rest of the queue. Or if for example there's an order which is too big and cannot be paid at the moment, this will cause also smaller orders further down the queue to not be paid (which may or may not be the intention here). You should consider continuing to execute orders in the queue if there's no reason to stop for all.

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                || receiver_ == address(orchestrator().fundingManager().token())
This is essentially making an external call for each time you validate. If this restriction doesn't have a specific important reason I'd suggest to remove it. And if it does I'd recommend to save the token in storage here instead of reading it every time.

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
This is especially true since there can be different payment tokens for different orders (in theory also if from the same client)

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
And another point, if the execution halts due to any of the reasons for _processNextOrder to return false, there's not option to continue the execution until the client processes more payments. It would make sense to allow users to also trigger payments as there seems to be no reason to force them to wait from new payments to be processed in order to be able to retry processing their own

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +        clientIsValid(address(client_))
_executePaymentQueue already checks clientIsValid. Though it's unclear to me why would you require the client itself only to trigger its payment and not allow it to be triggered also externally. If a user is willing to pay the gas for the execution, I see no security reason to prevent them from calling execute (assuming proper validation of the client being called)

2025-03-06 11:02 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +contract PP_Queue_ManualExecution_v1 is
For a payment queue, it seems to me more logical to have the default contract be manual execution, then have an extension contract offering automatic execution. That would both save code duplication you have in processPayments, and would make more sense in the context of queue, as the goal is usually to wait and execute multiple payments at once.

2025-03-06 11:02 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            RedemptionState.PENDING
Depending on the payment processor, the previous call to `processPayments` may have executed the order (and emitted a correspoding event with a PROCESSED redemption state). It is better to emit this even t _before_ execution

2025-03-06 11:02 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            revert Module__FM_PC_ExternalPrice_Redeeming_QueueExecutionFailed();
it is never a good idea to suppress error messages - you probably want to include the reason for the revert in the Error in some way

2025-03-10 10:25 UTC, Zitzak commented
@Zitzak 
- Remove `setSellFee` public function as we don't add any feature when overriding

2025-03-10 18:10 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        __Module_orchestrator.paymentProcessor().processPayments(
As we don't make a hard coupling between specific module, i.e. this FM and the Queue base PP, we decided to built the FM in a way that it would also work if someone would couple for example the PP_Simple_v1. For that reason, we call process payments, and if it isn't the `PP_Queue_ManualExecution_v1`, the PP would just go ahead and process each payment order. Hope this clarifies it

2025-03-10 18:31 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
I let @vendrell46 react to this as well in regard to your first comment. I have a few points to add to your comment:
- The Queue is first in, first out. So if the queue stops due to an order being too big then that is expected behaviour
- You are right that the `_processNextOrder` function would stop when an order fails. The possibility of an order failing has been added later to the contract, and apparently the tests have not caught this sadly.
- You are right in regard to the case that a client could have different payment tokens. Could you give a suggestions how you would stick to the "first in, first out" requirements while still accounting for multiple tokens? 
- Given the issue with the queue execution stopping when a transfer has failed is resolved we should be good in respect to the queue execution. The workflow owners should have the control over when to execute the queue
@omega-audits

2025-03-10 18:34 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                || receiver_ == address(orchestrator().fundingManager().token())
You are right here, however this is how we've done it in the other PPs as well, and we aim to be on networks with low gas costs. However going to bring this up internally. Thank you

2025-03-10 18:40 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +        clientIsValid(address(client_))
Agree on the `clientIsValid` check. Thank you. In regard to the question around why it can only be triggered through the client; the manual queue PP is coupled with a FM which may or may not hold assets to execute the redemption queue. The general flow would look something like this:
1. Tokens are minted in the FM, collateral withdrawn
2. Issued tokens are redeemed, but instead of a direct payout, a redemption queue order is created in the PP
3. Collateral reserve is deposited back into the FM (which also is the Payment Client) in preparation to executing the  queue
4. The queue is manually executed through the FM function `executeRedemptionQueue()` after which the collateral is pulled from the FM and processed for each order

Hope this clarifies some of the thinking behind the setup @omega-audits

2025-03-10 18:43 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +contract PP_Queue_ManualExecution_v1 is
So.. I think that makes sense in hindsight to do the naming and "default" queue based PP manual. I will check if it makes sense for us now to rename everything as the client has already started testing, and it has been integrated already in the Indexer etc. However fair point. 

In terms of code duplication, I would suspect that it is about the same

2025-03-10 18:45 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            RedemptionState.PENDING
Good point! We will move it. Thank you

2025-03-10 18:51 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            revert Module__FM_PC_ExternalPrice_Redeeming_QueueExecutionFailed();
The idea here was that the only reason it would fail is because the contract being called doesn't have the correct function. However we can add the `bytes data` from the call to the custom error

2025-03-11 06:25 UTC, vendrell46 commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
> If firstId != LinkedIdList._SENTINEL then _processNextOrder will return false, so the entire tracking here of firstId is essentially unnecessary

You are absolutely right, good catch. I will modify it as you suggested, @omega-audits

2025-03-12 09:29 UTC, jellegerbrandy commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        __Module_orchestrator.paymentProcessor().processPayments(
So this is of course not a bug, but our observation here is that if the PP has a queue, this queue is not used if you call processPrayments each time you add a payment order. In other words, our point is that this is not a good use of the queue-based PP.

2025-03-12 09:30 UTC, jellegerbrandy commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        __Module_orchestrator.paymentProcessor().processPayments(
That said, if this is clear to all of us, we can close this comment :)

2025-03-13 22:22 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +        clientIsValid(address(client_))
In this case though, why does it try to immediately execute each payment added to the queue (as mentioned in another comment above here)?

2025-03-21 18:45 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        _executePaymentQueue(address(client_));
We have done this with the manual version ser. Assuming that this was commented before you've seen that version :)

2025-03-23 17:30 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        while (firstId != LinkedIdList._SENTINEL && _processNextOrder(client_))
Has been addressed

2025-03-23 17:32 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +        clientIsValid(address(client_))
I believe you confuse the manual contract with the automatic one @omega-audits? The manual version which is referenced in the comment does not execute the payments right away

2025-03-23 17:32 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +contract PP_Queue_ManualExecution_v1 is
We will leave the name as is for now ser @omega-audits

2025-03-23 17:34 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            revert Module__FM_PC_ExternalPrice_Redeeming_QueueExecutionFailed();
Has been addressed

2025-03-23 17:35 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                || receiver_ == address(orchestrator().fundingManager().token())
We will leave it as is for now ser

2025-03-23 17:35 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            RedemptionState.PENDING
has been addressed

2025-03-30 13:00 UTC, omega-audits commented on src/external/token/ERC20IssuanceUpgradeable_Blacklist_v1.sol
> +        onlyBlacklistManager
It could be slightly more gas efficient to have an internal _ addToBlacklist without the modifier and use it both here and in the batched version, and add the onlyBlacklistManager to the batched function, so that the modifier is only executed once and not on each iteration. Same for the remove logic.

2025-03-30 13:00 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                revert Module__PP_Queue_InvalidFeeAmount(feeAmount_);
Are you sure you'd like to revert here in this case? 

If a payment order was for a very small amount, this could get the whole queue completely stuck, also for removing the payment which also uses this function (which is another point, when this function is used in cancelling a payment, there's no reason to take fees)

2025-03-30 13:00 UTC, omega-audits commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                revert Module__PP_Queue_InvalidFeeAmount(feeAmount_);
So I'd recommend:
1. Remove this revert check entirely
2. When cancelling a payment, pass a flag to the  tryPaymentTransfer to avoid calling this function

2025-03-30 13:01 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            amount: netCollateralRedeemAmount_ + protocolCollateralFeeAmount_,
So the Payment Processor will now be recalculating the fee, but using the redeemAmount + protocol fee as the total amount, instead of redeemAmount + protocol fee + project fee.

This will result in a potential slight underpayment of the fees.

2025-03-31 09:24 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +                revert Module__PP_Queue_InvalidFeeAmount(feeAmount_);
Good point ser @omega-audits. I'll remove the revert and implement the flag as suggested

2025-03-31 09:32 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            amount: netCollateralRedeemAmount_ + protocolCollateralFeeAmount_,
The project fee is never deposited back into the FM as total redeem amount for executing the queue. Because of that, we don't have the project here in the payment order amount ser @omega-audits . Does that make sense?

2025-03-31 13:21 UTC, omega-audits commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            amount: netCollateralRedeemAmount_ + protocolCollateralFeeAmount_,
No but what I mean is that the protocol fee is calculated here based on net redeem amount + protocol fee + project fee. So if total amount is 100, and the fees are 2 percent each, it'll pass 98 as the amount to the payment order, which is fine, but the problem is then that the payment processor is re calculating the protocol fee, but it'll do it as 2% of 98, instead of 2% of 100.

2025-03-31 13:39 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            amount: netCollateralRedeemAmount_ + protocolCollateralFeeAmount_,
Makes sense, thank you

2025-04-01 11:53 UTC, Zitzak commented on src/external/token/ERC20IssuanceUpgradeable_Blacklist_v1.sol
> +        onlyBlacklistManager
Agree

2025-04-01 12:58 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +            amount: netCollateralRedeemAmount_ + protocolCollateralFeeAmount_,
Discussed the issue internally and understood that a similar problem surfaced not long ago when dealing with a different client project, i.e. the fee being calculated twice in different locations which results in an underpayment of fee. The solution decided to move forward with in that case was to adjust the fee percentage upwards such that the fee amount collected would be as expected.

As we are currently working on a new FeeManager contract, which will enable a better mechanism of collecting fee across the workflows, we decided to go with the same manual adjustment approach for now.

We're aware that this solution is a temporary, manual bandaid and not an actual solution. However as no client or token receiver is negatively impacted by the current setup, and we are currently working on the new FeeManager and there is no clean solution we decided to move ahead with the way it is now. @omega-audits

2025-04-01 17:11 UTC, omega-audits commented on src/external/token/ERC20Issuance_Blacklist_v1.sol
> +        }
This is unnecessary since the add already checks so if account passed here is 0 nothing will happen

2025-04-06 21:26 UTC, omega-audits approved these changes

2025-04-10 09:34 UTC, jellegerbrandy commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
The state of the order will be canceled and the order removed from the queue also if the payment failed. Is that desired behavior?

2025-04-10 09:38 UTC, jellegerbrandy commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        (bool success, bytes memory data) = token_.call(
A `try... catch.. ` pattern would do the same thing, but you do not need to parse the resuts of a low-level call yourself

2025-04-10 09:59 UTC, jellegerbrandy commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        if (order.state_ != RedemptionState.PENDING) {
1. afaics thsi should never happen, as each time the state is changed from pending, the order is removed from the queue. So perhaps not fail silently here? 
2. If I am wrong and this happens, why return `false`? This will cause the loop in _executePaymentQueue to exit, and so the operator will need to call processPayments a second time to process the rest of the queue.

2025-04-11 05:54 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
Good point. In practise this should never 'fail' as we're sending it to project owners canceled orders treasury. Meaning that this address would have to be blacklisted by the project for it to fail. However it makes sense to add a revert in case this would happen anyway

2025-04-11 06:12 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
Good point. In practise this should never 'fail' as we're sending it to project owners canceled orders treasury. Meaning that this address would have to be blacklisted by the project for it to fail. However it makes sense to add a revert in case this would happen anyway

2025-04-11 09:27 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        (bool success, bytes memory data) = token_.call(
So it's also being tested with an address which doesn't have the transfer interface. I tried all kind of ways with `try/catch` but I didn't get it to work with the EVM revert which resulted from it. Eventually a colleague found this explanation for it not working, so I will stick with the low level call for now :)
![image (3)](https://github.com/user-attachments/assets/9717a384-5a86-4f69-b1f9-08315a861286)

2025-04-11 09:27 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        if (order.state_ != RedemptionState.PENDING) {
You're right it shouldn't happen, so going to revert instead of Fail here

2025-04-16 15:30 UTC, jellegerbrandy approved these changes
lgtm!

2025-04-16 18:08 UTC, FHieser reviewed
It took me more time to review this than anticipated.
Will give my feedback for the Queue PP tomorrow

2025-04-16 18:08 UTC, FHieser commented on .vscode/settings.json
Are these really part of the PR?

2025-04-16 18:08 UTC, FHieser commented on src/modules/logicModule/LM_Oracle_Permissioned_v1.sol
> +    uint[50] private __gap;
Why is this gap at the end of the file?
As it is a state modification I would argue that it fits better at the end of the State section

2025-04-16 18:08 UTC, FHieser commented on src/modules/logicModule/LM_Oracle_Permissioned_v1.sol
> +    function getCollateralTokenDecimals()
Would love to see a separation between Getter and Mutating Functions here

2025-04-16 18:08 UTC, FHieser commented on src/modules/logicModule/LM_Oracle_Permissioned_v1.sol
> +    function getCollateralTokenDecimals()
Getter being first and then Mutating

2025-04-16 18:08 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +    function getBuyFee() public view virtual returns (uint buyFee_) {
Seperation from view and not view functions section please

2025-04-16 18:08 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        _deductFromOpenRedemptionAmount(amount_);
Can you explain to me what exactly is the difference between Amount paid and Open Redemption amount?

2025-04-16 18:08 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +    uint[50] private __gap;
Gap here

2025-04-16 18:08 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
I think I would have loved to see a general implementation here first (only the Oracle Functionality)
And then a more specific solution, kinda like we did it for Topos.
I know that is to late for this implementation now, but I think it would be great if you guys could write an outlier of which functionalities could be abstracted into the general and specific implementation respectively, to make it easier at a later point of time to get into it again

2025-04-16 18:08 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        _deductFromOpenRedemptionAmount(amount_);
I did not dig into this fully, but my first perception is, that they could be the same value essentially

2025-04-16 18:27 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
I think this is great feedback for the modules that we are currently building if I understood correctly. I'm constantly trying to figure out what can be abstracted during development but would be nice to review this beforehand so we go into the work already thinking of the abstracting away as much as possible.

2025-04-16 18:32 UTC, leeftk commented on src/modules/logicModule/LM_Oracle_Permissioned_v1.sol
> +    uint[50] private __gap;
For some reason these keep getting added, maybe we need to add this to the .gitignore, but we had the same issue on the other module. Will look for @zitzak guidance on this as it seems to be recurring.

2025-04-16 18:35 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +    uint[50] private __gap;
Checked the OZ docs and @FHieser is correct this can be placed anywhere in the file though I have seen a lot of projects place it at the end like this, not sure why though as there's no specific reason

2025-04-16 18:38 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +    uint[50] private __gap;
Here's an example.
https://github.com/forta-network/forta-contracts/blob/ad2a47a28cf0dd1913caf28b0f498f84aceec34e/contracts/vesting/VestingWalletV1.sol

2025-04-17 09:27 UTC, FHieser requested changes
See comments

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function unclaimable(
View Function in Mutating Section

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function validPaymentOrder(
same here

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
There is an argument that could be made here, for actually taking a protocol fee here, as tokens get actually routed through the workflow itself and land in a private treasury. Do you have any opinions of this @Zitzak @marvinkruse @0xNuggan

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    uint[50] private __gap;
Gap

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function _addToUnclaimableAmount(
Is this function used anywhere?

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function claimPreviouslyUnclaimable(
Am I misreading things or is the accesscontrol here missing?
Shouldnt it be reveiver = _msgSender()?

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        }
If it doesnt have the correct flags, then it always returns queueId of 0, which can result in multiple payment orders having the same id. Does that pose a problem?
What happens when a queue Id is duplicated?

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function _validPaymentOrder(
For later reference, as its too late for that now, but:
For clean code purposes I think the _validPaymentOrder function and most of the sub functions in here could probably be moved into a abstract PaymentProcessor contract as they provide a general solution in most cases. Examples are:
- _validTotalamount
- _validChainId
- _validPaymentToken

You could also just call super._validPaymentOrder and && the paymentQueueId here into the bool operation.
@leeftk Dont know your work for the next project, but if you guys are working on another PP then this might be something that we could adapt in the future
@marvinkruse You think thats viable here? I think that could be worth to create an issue for that.

2025-04-17 09:27 UTC, FHieser commented on src/modules/paymentProcessor/PP_Queue_ManualExecution_v1.sol
> +    uint[50] private __gap;
Gap

2025-04-17 09:36 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
Yeah its a learning process, some things only make sense when there was some substantial development in the first place and then its hard to look at it from a broader viewpoint.
If you want some feedback on the upcoming project feel free to just reach out to me :D

2025-04-17 17:45 UTC, Zitzak commented on src/modules/logicModule/LM_Oracle_Permissioned_v1.sol
> +    uint[50] private __gap;
@leeftk your message refers to the `settings.json` I believe?

2025-04-17 17:50 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
I'm not sure if it makes sense to split the implementation up more then currently is, as the oracle functionality heavily uses the bonding curve base setup i.e. we are using the base and changing the formula wrapper functions to call an oracle rather then a formula contract. Practically speaking this means a setter & getter and the wrapper functions which creating an extra base contract might be overkill.

In general of course I agree with the statement of abstraction

2025-04-22 17:28 UTC, Zitzak commented on .vscode/settings.json
Not sure how they sneak in everytime. Deleted

2025-04-22 18:07 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        }
So we call `_validPaymentOrder()` before adding a payment order. Within the check we call `_validQueueId()` with the queueID that is returned from this function. It checks the order or queue IDs, ensuring no IDs can be duplicated

2025-04-22 18:08 UTC, Zitzak commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +    function _validPaymentOrder(
Agree, we should move towards building an abstract PP that all implementations of the PP can inherit from

2025-04-22 18:43 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        _deductFromOpenRedemptionAmount(amount_);
So looked into it and indeed the Amount Paid value could have been used for it. Overlooked it. However we did add events that are emitted when the open redemption amount is added/deducted, which are picked up by the indexer and platform. This is a feature which the underlying Amount Paid did not have.

Due to that reason I would not remove the current setup as the emitted event are needed, and adding them to the base contract is not straight forward. Wdyt @FHieser ?

2025-04-23 01:08 UTC, marvinkruse commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
I remember that you brought this up to me in a huddle. I am not sure whether there are any more info in terms of what is going to happen with cancelled payments, but overall I think I agree. As far as our system is concerned, the payment is done, and the reason of failure is most likely not on our side. What do you think @0xNuggan?

2025-04-23 07:26 UTC, FHieser commented on src/modules/fundingManager/oracle/FM_PC_Oracle_Redeeming_v1.sol
> +        _deductFromOpenRedemptionAmount(amount_);
There is a right and a fast answer here:
The right one is to rework it, the fast one is you dont, as the only thing it does is "duplicate" code
Create a issue for it and this should be fine

2025-04-23 12:12 UTC, 0xNuggan commented on src/modules/paymentProcessor/PP_Queue_v1.sol
> +        success_ = _tryPaymentTransfer(
Discussed this with Ata: For now we are going with no fee on canceled or failed transfers. If we see projects exploiting this in the future, we can reassess.

2025-04-23 12:18 UTC, FHieser approved these changes

2025-04-23 14:01 UTC, merged