FM_PC_ExternalPrice_Redeeming_v1_Test
InverterNetwork/inverter-contracts pull request #706
Opened 2024-12-22 16:33 UTC by scab24

Tests for the contract:

- [FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol](https://github.com/ZealynxSecurity/InverterContracts/blob/G-dev-1-test/test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol)
- [LM_ManualExternalPriceSetter_v1_Test.t.sol](https://github.com/ZealynxSecurity/InverterContracts/blob/G-dev-1-test/test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol)

2025-01-08 18:12 UTC, Zitzak requested changes
Only reviewed implementation. Will be looking into the testing now

2025-01-08 18:12 UTC, Zitzak commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    ) external onlyModuleRole(PRICE_SETTER_ROLE) {
Seems like we're duplicating some code here. I think we should be adding internal functions for both the redemption and isuance price which then can be called through this function

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            depositAmount_,
The token decimal changes as well as the calculation for the min amount probably snug back in through the rebasing. Those change were made when deploying. So what has been changed here needs to be reverted again

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> +            tokenAmount_, EIGHTEEN_DECIMALS, _collateralTokenDecimals
See comment above about reverting these changes

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> -    function _deductFromOpenRedemptionAmount(uint processedRedemptionAmount_)
Will still be needed. Shouldn't be removed

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
>              _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
Just noticing a mistake here. We shouldn't pass the `issuanceFeeAmount` but `projectFeeAmount`


```suggestion
            _receiver, _depositAmount, collateralRedeemAmount, projectFeeAmount
```

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_ExternalPrice_Redeeming_v1.sol
> -    /// @param  redemptionAmount The new open redemption amount.
Should not be removed

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/interfaces/IFM_PC_ExternalPrice_Redeeming_v1.sol
> -    /// @param  processedRedemptionAmount_ The amount of redemption tokens that
Should not be removed

2025-01-08 18:12 UTC, Zitzak commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
> -    function deductProcessedRedemptionAmount(uint processedRedemptionAmount_)
Should not be removed

2025-01-08 19:12 UTC, Zitzak requested changes
I'm finding a lot of things setup wise which should be changed. Part of this is probably also on me as I could have been involved earlier.

I will be stopping the review for today but continue tomorrow. Also I'm updating most of the points I'm noticing on a branch at the same time while reviewing as it is probably a lot easier for me to go in and change it right away.

Will keep you updated!

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +contract LM_ManualExternalPriceSetter_v1_Test is ModuleTest {
File should be moved to the Logic Module folder

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/token/utils/mocks/ERC20Issuance_blacklist_v1_exposed.sol
> +contract ERC20Issuance_Blacklist_v1_Exposed is ERC20Issuance_Blacklist_v1 {
Should be moved to the external folder. Same as the access mock

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/OraclePriceMock.sol
> +contract OraclePriceMock is IOraclePrice_v1, ERC165 {
Not used anywhere. Can this be removed?

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +        InvalidOracleMock invalidOracle = new InvalidOracleMock();
```suggestion
        address invalidOracle = makeAddr("InvalidOracleMock");
```

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +        InvalidOracleMock invalidOracle = new InvalidOracleMock();
Could be achieved with using a one time address that would also revert. This means we can remove the Invalid Oracle mock I belive

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/MockERC20.sol
> +contract MockERC20 is ERC20 {
We already have a mock token in the repo at `test/utils/mocks/ERC20Mock.sol`. This contract can be removed ser

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        inputToken = new MockERC20(6); // Like USDC
The inherited `ModuleTest` contract already exposes an ERC20 Mock token with the variable name `_token`. This can be used. Additionally the ERC20 mock which we already have in the repo should be used when needing additional tokens for testing

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/MockERC20.sol
> +contract MockERC20 is ERC20 {
Seeing now that you need decimals for your testing as well. Would still be good to than extend the current mock and add decimals. Also I couldn't find that you were using other function of this mock anyway

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +    PP_Streaming_v1,
Lots of unused imports ser

2025-01-08 19:12 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +        address PaymentImpl = address(new PP_Streaming_v1AccessMock());
Not sure why the default PP that is deployed in the `ModuleTest` isn't used?

2025-01-09 16:22 UTC, Zitzak requested changes

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +contract FM_PC_ExternalPrice_Redeeming_v1_Test is ModuleTest {
Rename file to reflect the implementation contract name (see code of conduct document)

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +contract FM_PC_ExternalPrice_Redeeming_v1_Test is ModuleTest {
Same for the other test files

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        authorizer = new AuthorizerV1Mock();
The `ModuleTest` contract inherited from already deployes the authorizer. It is basically being redeployed here and then assigned, mirroring what happens in the `ModuleTest` contract. This can be removed

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        address impl = address(new LM_ManualExternalPriceSetter_v1());
The `LM_ManualExternalPriceSetter_v1_Exposed()` contract can be directly used for all internal and external/public function testing. We don't need to deploy two versions for this

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        address impl = address(new LM_ManualExternalPriceSetter_v1());
All of the init can be removed as well

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/LM_ManualExternalPriceSetter_v1_exposed.sol
> +    function exposed_authorizer() external view returns (IAuthorizer_v1) {
Not used anywhere

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/LM_ManualExternalPriceSetter_v1_exposed.sol
> +import {IOrchestrator_v1} from "src/orchestrator/interfaces/IOrchestrator_v1.sol";
Usnused imports can be removed

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +
We don't have an access mock (exposed) contract for testing. This means no internal functions have been tested

2025-01-09 16:22 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +    function setUp() public {
Most of the setup should be done differently and has been implemented in the PR I opened

2025-01-09 23:22 UTC, leeftk commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        inputToken = new MockERC20(6); // Like USDC
This may be a bit of a naive question on my part so apologies but Im not seeing where we can adjust the decimals for the ERC20Mock that is already provided for us, could this be the reason that @scab24 decided to create a new contract? In this case this ERC20 has 6 decimals

2025-01-10 00:00 UTC, leeftk commented on test/modules/fundingManager/oracle/utils/mocks/OraclePriceMock.sol
> +contract OraclePriceMock is IOraclePrice_v1, ERC165 {
Yes I removed this in the latest PR

2025-01-10 00:36 UTC, leeftk commented on src/modules/logicModule/LM_ManualExternalPriceSetter_v1.sol
> +    ) external onlyModuleRole(PRICE_SETTER_ROLE) {
Made this change in my latest PR

2025-01-10 00:36 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
>              _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
Made this change in my latest PR

2025-01-10 04:14 UTC, leeftk commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        inputToken = new MockERC20(6); // Like USDC
I saw your implementation of this on your PR please disregard this comment

2025-01-10 09:08 UTC, Zitzak commented on test/modules/fundingManager/oracle/utils/mocks/OraclePriceMock.sol
> +contract OraclePriceMock is IOraclePrice_v1, ERC165 {
I already removed it as well within my PR, that I just merged @leeftk, fyi

2025-01-10 09:09 UTC, Zitzak commented on test/modules/fundingManager/oracle/LM_ManualExternalPriceSetter_v1_Test.t.sol
> +        inputToken = new MockERC20(6); // Like USDC
Yes you are right, and I noticed that we didn't have the ability to set decimals. I indeed ended up implementing it as defined in this [comment](https://github.com/InverterNetwork/contracts/pull/706#discussion_r1907657810)

2025-01-10 09:11 UTC, Zitzak commented on test/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1_Test.t.sol
> +
Leaving this one open as a reminder to do the internal function testing. The access mock got added through my PR

2025-01-16 09:40 UTC, Zitzak commented
Closing this PR, as all the changes have been merged into [ZealynxSecurity/Feature/FM_PC_ExternalPrice](https://github.com/ZealynxSecurity/InverterContracts/tree/ZealynxSecurity/Feature/FM_PC_ExternalPrice) branch
@vendrell46 @scab24 @leeftk

2025-01-16 09:40 UTC, closed without merging

2025-01-16 18:35 UTC, leeftk commented on src/modules/fundingManager/oracle/FM_PC_ExternalPrice_Redeeming_v1.sol
>              _receiver, _depositAmount, collateralRedeemAmount, issuanceFeeAmount
Addressed in the feature branch